<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountiesSeeder extends Seeder
{
    public function run(): void
    {
        $municipiosPorEstado = [
            7 => [
                'ACANDIÁN',
                'ACAPETAH',
                'ALBERTO GARCÍA',
                'ALTAMIRANO',
                'AMATÁN',
                'ARRIAGA',
                'BEJUCAL DE OCAMPO',
                'BELISARIO DOMÍNGUEZ',
                'BENITO JUÁREZ',
                'BERRIOZÁBAL',
                'BOCHIL',
                'CACAHOATÁN',
                'CATAZAJÁ',
                'CHAMULA',
                'CHENALHÓ',
                'CHIAPA DE CORZO',
                'CHICOASÉN',
                'CHILÓN',
                'COPAINALÁ',
                'COTZOCÓN',
                'FRANCISCO LEÓN',
                'FRANCISCO RIVERA',
                'HUITIUPÁN',
                'IXTAPA',
                'JITOTOL',
                'LA TRINITARIA',
                'LARRAINZAR',
                'MAPASTEPEC',
                'MOTOZINTLA',
                'NUEVO ORIZABA',
                'OCOSINGO',
                'OCOZOCALCO',
                'PANTELÓ',
                'PICHUCALCO',
                'PRACTICANTE',
                'RAYÓN',
                'SAN CRISTÓBAL DE LAS CASAS',
                'SAN FERNANDO',
                'SAN JERÓNIMO',
                'SAN LUIS',
                'SAN MARCOS',
                'SAN MIGUEL',
                'SAN SALVADOR',
                'SILTEPEC',
                'TAPACHULA',
                'TUXTLA GUTIÉRREZ',
                'VILLAFLORES',
            ],
            27 => [
                'BALANCÁN',
                'CÁRDENAS',
                'CENTLA',
                'CENTRO',
                'COMALCALCO',
                'CUNDUACÁN',
                'EMILIANO ZAPATA',
                'HUIMANGUILLO',
                'JALAPA',
                'JALPA DE MÉNDEZ',
                'JONUTA',
                'MACUSPANA',
                'NACAJUCA',
                'PARAÍSO',
                'TACOTALPA',
                'TEAPA',
                'TENOSIQUE'
            ],
            4 => [
                'CALAKMUL',
                'CAMPECHE',
                'CANDELARIA',
                'CALKINÍ',
                'CARMEN',
                'CHAMPOTÓN',
                'ESCÁRCEGA',
                'HECELCHAKÁN',
                'HOPELCHÉN',
                'PALIZADA',
                'TENABO'
            ],
            31 => [
                'ABALÁ',
                'ACANCEH',
                'AKIL',
                'BACA',
                'BOKOBÁ',
                'BUCTZOTZ',
                'CACALCHÉN',
                'CALOTMUL',
                'CANSAHCAB',
                'CANTAMAYEC',
                'CELESTÚN',
                'CENOTILLO',
                'CONKAL',
                'CUNCUNUL',
                'CUZAMÁ',
                'CHACSINKÍN',
                'CHANKOM',
                'CHAPAB',
                'CHEMAX',
                'CHICXULUB PUEBLO',
                'CHICHIMILÁ',
                'CHIKINDZONOT',
                'CHOCHOLÁ',
                'CHUMAYEL',
                'DZAN',
                'DZEMUL',
                'DZIDZANTÚN',
                'DZILAM DE BRAVO',
                'DZILAM GONZÁLEZ',
                'DZITÁS',
                'DZONCAUICH',
                'ESPITA',
                'HALACHÓ',
                'HOCABÁ',
                'HOCTÚN',
                'HOMÚN',
                'HUHÍ',
                'HUNUCMÁ',
                'IXIL',
                'IZAMAL',
                'KANASÍN',
                'KANTUNIL',
                'KAUA',
                'KINCHIL',
                'KOPOMÁ',
                'MAMA',
                'MANÍ',
                'MAXCANÚ',
                'MAYAPÁN',
                'MÉRIDA',
                'MOCOCHÁ',
                'MOTUL',
                'MUNA',
                'MUXUPIP',
                'OPICHÉN',
                'OXKUTZCAB',
                'PANABÁ',
                'PETO',
                'PROGRESO',
                'QUINTANA ROO',
                'RÍO LAGARTOS',
                'SACALUM',
                'SAMAHIL',
                'SANAHCAT',
                'SAN FELIPE',
                'SANTA ELENA',
                'SEYÉ',
                'SINANCHÉ',
                'SOTUTA',
                'SUCILÁ',
                'SUDZAL',
                'SUMA DE HIDALGO',
                'TAHDZIÚ',
                'TAHMEK',
                'TEABO',
                'TECÓH',
                'TEKAL DE VENEGAS',
                'TEKANTÓ',
                'TEKAX',
                'TEKIT',
                'TEKOM',
                'TELCHAC PUEBLO',
                'TELCHAC PUERTO',
                'TEMAX',
                'TEMOZÓN',
                'TEPAKÁN',
                'TETIZ',
                'TEYA',
                'TICUL',
                'TIMUCUY',
                'TINUM',
                'TIXCACALCUPUL',
                'TIXKOKOB',
                'TIXMÉHUAC',
                'TIXPÉHUAL',
                'TIZIMÍN',
                'TUNKÁS',
                'TZUCACAB',
                'UAYMA',
                'UCÚ',
                'UMÁN',
                'VALLADOLID',
                'XOCCHÉL',
                'YAXCABÁ',
                'YAXKUKUL',
                'YOBAÍN'
            ],
            23 => [
                'BACALAR',
                'BENITO JUÁREZ',
                'COZUMEL',
                'FELIPE CARRILLO PUERTO',
                'ISLA MUJERES',
                'JOSÉ MARÍA MORELOS',
                'LÁZARO CÁRDENAS',
                'OTHÓN P. BLANCO',
                'PUERTO MORELOS',
                'SOLIDARIDAD',
                'TULUM'
            ],
           5=> [
                'ABASOLO',
                'ACUÑA',
                'ALLENDE',
                'ARTEAGA',
                'CANDELA',
                'CASTAÑOS',
                'CUATRO CIÉNEGAS',
                'ESCOBEDO',
                'FRANCISCO I. MADERO',
                'FRONTERA',
                'GENERAL CEPEDA',
                'GUERRERO',
                'HIDALGO',
                'JIMÉNEZ',
                'JUÁREZ',
                'LAMADRID',
                'MATAMOROS',
                'MONCLOVA',
                'MORELOS',
                'MUZQUIZ',
                'NADADORES',
                'NAVA',
                'OCAMPO',
                'PARRAS',
                'PIEDRAS NEGRAS',
                'PROGRESO',
                'RAMOS ARIZPE',
                'SABINAS',
                'SACRAMENTO',
                'SALTILLO',
                'SAN BUENAVENTURA',
                'SAN JUAN DE SABINAS',
                'SAN PEDRO',
                'SIERRA MOJADA',
                'TORREÓN',
                'VIESCA',
                'ZARAGOZA'
            ],
            30 => [
                'ACAJETE',
                'ACATLÁN',
                'ACAYUCAN',
                'ACTOPAN',
                'ACULA',
                'ACULTZINGO',
                'AGUA DULCE',
                'ÁLAMO TEMAPACHE',
                'ALPATLÁHUAC',
                'ALTO LUCERO DE GUTIÉRREZ BARRIOS',
                'ALTOTONGA',
                'ALVARADO',
                'AMATITLÁN',
                'AMATLÁN DE LOS REYES',
                'ÁNGEL R. CABADA',
                'LA ANTIGUA',
                'APAZAPAN',
                'AQUILA',
                'ASTACINGA',
                'ATLAHUILCO',
                'ATOYAC',
                'ATZACAN',
                'ATZALAN',
                'AYAHUALULCO',
                'BANDERILLA',
                'BENITO JUÁREZ',
                'BOCA DEL RÍO',
                'CALCAHUALCO',
                'CAMARÓN DE TEJEDA',
                'CAMERINO Z. MENDOZA',
                'CARRILLO PUERTO',
                'CATEMACO',
                'CAZONES DE HERRERA',
                'CERRO AZUL',
                'CITLALTÉPETL',
                'COACOATZINTLA',
                'COAHUITLÁN',
                'COATEPEC',
                'COATZACOALCOS',
                'COATZINTLA',
                'COETZALA',
                'COLIPA',
                'COMAPA',
                'CÓRDOBA',
                'COSAMALOAPAN DE CARPIO',
                'COSAUTLÁN DE CARVAJAL',
                'COSCOMATEPEC',
                'COSOLEACAQUE',
                'COTAXTLA',
                'COXQUIHUI',
                'COYUTLA',
                'CUICHAPA',
                'CHACALTIANGUIS',
                'CHALMA',
                'CHICONAMEL',
                'CHICONQUIACO',
                'CHICONTEPEC',
                'CHINAMECA',
                'CHINAMPA DE GOROSTIZA',
                'CHOCAMÁN',
                'CHONTLA',
                'CHUMATLÁN',
                'EMILIANO ZAPATA',
                'ESPINAL',
                'FILOMENO MATA',
                'FORTÍN',
                'GUTIÉRREZ ZAMORA',
                'HIDALGOTITLÁN',
                'HUATUSCO',
                'HUAYACOCOTLA',
                'HUEYAPAN DE OCAMPO',
                'HUILOAPAN DE CUAUHTÉMOC',
                'IGNACIO DE LA LLAVE',
                'ILAMATLÁN',
                'ISLA',
                'IXCATEPEC',
                'IXHUACÁN DE LOS REYES',
                'IXHUATLÁN DEL CAFÉ',
                'IXHUATLANCILLO',
                'IXHUATLÁN DEL SURESTE',
                'IXHUATLÁN DE MADERO',
                'IXMATLAHUACAN',
                'IXTACZOQUITLÁN',
                'JALACINGO',
                'XALAPA',
                'JALCOMULCO',
                'JÁLTIPAN',
                'JAMAPA',
                'JESÚS CARRANZA',
                'XICO',
                'JILOTEPEC',
                'JUAN RODRÍGUEZ CLARA',
                'JUCHIQUE DE FERRER',
                'LANDERO Y COSS',
                'LERDO DE TEJADA',
                'MAGDALENA',
                'MALTRATA',
                'MANLIO FABIO ALTAMIRANO',
                'MARIANO ESCOBEDO',
                'MARTÍNEZ DE LA TORRE',
                'MECATLÁN',
                'MECAYAPAN',
                'MEDELLÍN DE BRAVO',
                'MIAHUATLÁN',
                'LAS MINAS',
                'MINATITLÁN',
                'MISANTLA',
                'MIXTLA DE ALTAMIRANO',
                'MOLOACÁN',
                'NAOLINCO',
                'NARANJAL',
                'NARANJOS AMATLÁN',
                'NAUTLA',
                'NOGALES',
                'OLUTA',
                'OMEALCA',
                'ORIZABA',
                'OTATITLÁN',
                'OZULUAMA DE MASCARÑAS',
                'PAJAPAN',
                'PÁNUCO',
                'PAPANTLA',
                'PASO DEL MACHO',
                'LA PERLA',
                'PEROTE',
                'PLATÓN SÁNCHEZ',
                'PLAYA VICENTE',
                'POZA RICA DE HIDALGO',
                'LAS VIGAS DE RAMÍREZ',
                'RAFAEL DELGADO',
                'RAFAEL LUCIO',
                'LOS REYES',
                'RÍO BLANCO',
                'SALTABARRANCA',
                'SAN ANDRÉS TENEJAPAN',
                'SAN ANDRÉS TUXTLA',
                'SAN JUAN EVANGELISTA',
                'SANTIAGO SOCHIAPAN',
                'SANTIAGO TUXTLA',
                'SAYULA DE ALEMÁN',
                'SOCONUSCO',
                'SOCHIAPA',
                'SOLEDAD ATZOMPA',
                'SOLEDAD DE DOBLADO',
                'SOTEAPAN',
                'TAMALÍN',
                'TAMIAHUA',
                'TAMPICO ALTO',
                'TANCoco',
                'TANTIMA',
                'TANTOYUCA',
                'TATATILA',
                'CASTILLO DE TEAYO',
                'TECOLUTLA',
                'TEHUIPANGO',
                'TEMAPACHE',
                'TEMPOAL',
                'TENAMPA',
                'TENOCHTITLÁN',
                'TEOCELO',
                'TEPATLAXCO',
                'TEPETLÁN',
                'TEPETZINTLA',
                'TEQUILA',
                'JOSÉ AZUETA',
                'TEXCATEPEC',
                'TEXHUACÁN',
                'TEXISTEPEC',
                'TEZONAPA',
                'TIERRA BLANCA',
                'TIHUATLÁN',
                'TLACOJALPAN',
                'TLACOLULAN',
                'TLACOTALPAN',
                'TLACOTEPEC DE MEJÍA',
                'TLACHICHILCO',
                'TLALIXCOYAN',
                'TLALNELHUAYOCAN',
                'TLAPACOYAN',
                'TLAQUILPA',
                'TLILAPAN',
                'TOMATLÁN',
                'TONAYÁN',
                'TOTUTLA',
                'TUXPAN',
                'TUXTILLA',
                'ÚRSULO GALVÁN',
                'VEGA DE ALATORRE',
                'VERACRUZ',
                'VILLA ALTA',
                'XOXOCOTLA',
                'YANGA',
                'YECUATLA',
                'ZACUALPAN',
                'ZARAGOZA',
                'ZENTLA',
                'ZONGOLICA',
                'ZONCUAUTLA',
                'ZOZOCOLCO DE HIDALGO'
            ],
            20 => [
                'ABEJONES',
                'ACATLÁN DE PÉREZ FIGUEROA',
                'ASUNCIÓN CACALOTEPEC',
                'ASUNCIÓN CUYOTEPEJI',
                'ASUNCIÓN IXTALTEPEC',
                'ASUNCIÓN NOCHIXTLÁN',
                'ASUNCIÓN OCOTLÁN',
                'ASUNCIÓN TLACOLULITA',
                'AYOQUEZCO DE ALDAMA',
                'AYOTZINTEPEC',
                'CALIHUALÁ',
                'CANDELARIA LOXICHA',
                'CAPULÁLPAM DE MÉNDEZ',
                'CHAHUITES',
                'CHALCATONGO DE HIDALGO',
                'CHIQUIHUITLÁN DE BENITO JUÁREZ',
                'CIENEGA DE ZIMATLÁN',
                'CIUDAD IXTEPEC',
                'COATECAS ALTAS',
                'COICOYÁN DE LAS FLORES',
                'CONCEPCIÓN BUENAVISTA',
                'CONCEPCIÓN PÁPALO',
                'CONSTANCIA DEL ROSARIO',
                'COSOLAPA',
                'COSOLTEPEC',
                'CUILÁPAM DE GUERRERO',
                'CUYAMECALCO VILLA DE ZARAGOZA',
                'EL BARRIO DE LA SOLEDAD',
                'EL ESPINAL',
                'ELOXOCHITLÁN DE FLORES MAGÓN',
                'FRESNILLO DE TRUJANO',
                'GUADALUPE DE RAMÍREZ',
                'GUADALUPE ETLA',
                'GUELATAO DE JUÁREZ',
                'GUEVEA DE HUMBOLDT',
                'HEROICA CIUDAD DE EJUTLA DE CRESPO',
                'HEROICA CIUDAD DE HUAJUAPAN DE LEÓN',
                'HEROICA CIUDAD DE TLAXIACO',
                'HUAUTLA DE JIMÉNEZ',
                'IXPANTEPEC NIEVES',
                'IXTLÁN DE JUÁREZ',
                'JUCHITÁN DE ZARAGOZA',
                'JUQUILA',
                'JUQUILA VILLA DE GUADALUPE',
                'LA COMPAÑÍA',
                'LA PE',
                'LA REFORMA',
                'LOMA BONITA',
                'MAGDALENA APASCO',
                'MAGDALENA JALTEPEC',
                'MAGDALENA MIXTEPEC',
                'MAGDALENA OCOTLÁN',
                'MAGDALENA PEÑASCO',
                'MAGDALENA TEITIPAC',
                'MAGDALENA TEQUISISTLÁN',
                'MAGDALENA TLACOTEPEC',
                'MAGDALENA YODOCONO DE PORFIRIO DÍAZ',
                'MAGDALENA ZAHUATLÁN',
                'MARISCALA DE JUÁREZ',
                'MÁRTIRES DE TACUBAYA',
                'MATÍAS ROMERO AVENDAÑO',
                'MAZATLÁN VILLA DE FLORES',
                'MESONES HIDALGO',
                'MIÁHUATLÁN DE PORFIRIO DÍAZ',
                'MINAS DE SANTA MARTA',
                'MIXISTLÁN DE LA REFORMA',
                'MONJAS',
                'MORELOS',
                'MOTECRISTO DE GUERRERO',
                'MOTINZINTLA',
                'MUNDO NUEVO',
                'NATIVIDAD',
                'NAZARENO ETLA',
                'NEJAPA DE MADERO',
                'NUEVO ZOQUIAPAM',
                'OAXACA DE JUÁREZ',
                'OCOTLÁN DE MORELOS',
                'PINOTEPA DE DON LUIS',
                'PLUMA HIDALGO',
                'PUTLA VILLA DE GUERRERO',
                'REFORMA DE PINEDA',
                'REYES METZONTLA',
                'ROJAS DE CUAUHTÉMOC',
                'SALINA CRUZ',
                'SAN AGUSTÍN AMATENGO',
                'SAN AGUSTÍN ATENANGO',
                'SAN AGUSTÍN CHAYUCO',
                'SAN AGUSTÍN DE LAS JUNTAS',
                'SAN AGUSTÍN ETLA',
                'SAN AGUSTÍN LOXICHA',
                'SAN AGUSTÍN TLACOTEPEC',
                'SAN AGUSTÍN YATARENI',
                'SAN ANDRÉS CABECERA NUEVA',
                'SAN ANDRÉS DINICUITI',
                'SAN ANDRÉS HUAXPALTEPEC',
                'SAN ANDRÉS HUAYÁPAM',
                'SAN ANDRÉS IXTLAHUACA',
                'SAN ANDRÉS LAGUNAS',
                'SAN ANDRÉS NUXIÑO',
                'SAN ANDRÉS PAXTLÁN',
                'SAN ANDRÉS SOLAGA',
                'SAN ANDRÉS TEOTILÁLPAM',
                'SAN ANDRÉS TEPETLAPA',
                'SAN ANDRÉS YAÁ',
                'SAN ANDRÉS ZABACHE',
                'SAN ANDRÉS ZAUTLA',
                'SAN ANTONINO CASTILLO VELASCO',
                'SAN ANTONINO EL ALTO',
                'SAN ANTONINO MONTE VERDE',
                'SAN ANTONIO ACUTLA',
                'SAN ANTONIO DE LA CAL',
                'SAN ANTONIO HUITEPEC',
                'SAN ANTONIO NANAHUATÍPAM',
                'SAN ANTONIO SINICAHUA',
                'SAN ANTONIO TEPETLAPA',
                'SAN BALTAZAR CHICHICÁPAM',
                'SAN BALTAZAR LOXICHA',
                'SAN BALTAZAR YATZACHI EL BAJO',
                'SAN BARTOLO COYOTEPEC',
                'SAN BARTOLO SÓYALTEPEC',
                'SAN BARTOLO YAUTEPEC',
                'SAN BARTOLOMÉ AYAUTLA',
                'SAN BARTOLOMÉ LOXICHA',
                'SAN BARTOLOMÉ QUIALANA',
                'SAN BARTOLOMÉ YUCUAÑE',
                'SAN BARTOLOMÉ ZOOGOCHO',
                'SAN BERNARDO MIXTEPEC',
                'SAN BLAS ATEMPA',
                'SAN CARLOS YAUTEPEC',
                'SAN CRISTÓBAL AMATLÁN',
                'SAN CRISTÓBAL AMOLTEPEC',
                'SAN CRISTÓBAL LACHIRIOAG',
                'SAN CRISTÓBAL SUCHIXTLAHUACA',
                'SAN DIONISIO DEL MAR',
                'SAN DIONISIO OCOTEPEC',
                'SAN ESTEBAN ATATLAHUCA',
                'SAN FELIPE JALAPA DE DÍAZ',
                'SAN FELIPE TEJALÁPAM',
                'SAN FELIPE USILA',
                'SAN FRANCISCO CAHUACUÁ',
                'SAN FRANCISCO CAJONOS',
                'SAN FRANCISCO CHAPULAPA',
                'SAN FRANCISCO CHINDÚA',
                'SAN FRANCISCO DEL MAR',
                'SAN FRANCISCO HUEHUETLÁN',
                'SAN FRANCISCO IXHUATÁN',
                'SAN FRANCISCO JALTEPETONGO',
                'SAN FRANCISCO LACHIGOLÓ',
                'SAN FRANCISCO LOGUECHE',
                'SAN FRANCISCO NUXAÑO',
                'SAN FRANCISCO OZOLOTEPEC',
                'SAN FRANCISCO SOLA',
                'SAN FRANCISCO TELIXTLAHUACA',
                'SAN FRANCISCO TEOPAN',
                'SAN FRANCISCO TLAPANCINGO',
                'SAN GABRIEL MIXTEPEC',
                'SAN ILDEFONSO AMATLÁN',
                'SAN ILDEFONSO SOLA',
                'SAN ILDEFONSO VILLA ALTA',
                'SAN JACINTO AMILPAS',
                'SAN JACINTO TLACOTEPEC',
                'SAN JERÓNIMO COATLÁN',
                'SAN JERÓNIMO SILACAYOAPILLA',
                'SAN JERÓNIMO SOSOLA',
                'SAN JERÓNIMO TAVICHE',
                'SAN JERÓNIMO TECOATL',
                'SAN JORGE NUCHITA',
                'SAN JOSÉ AYUQUILA',
                'SAN JOSÉ CHILTEPEC',
                'SAN JOSÉ DEL PEÑASCO',
                'SAN JOSÉ DEL PROGRESO',
                'SAN JOSÉ ESTANCIA GRANDE',
                'SAN JOSÉ INDEPENDENCIA',
                'SAN JOSÉ LACHIGUIRI',
                'SAN JOSÉ TENANGO',
                'SAN JUAN ACHIUTLA',
                'SAN JUAN ATEPEC',
                'SAN JUAN BAUTISTA ATATLAHUCA',
                'SAN JUAN BAUTISTA COIXTLAHUACA',
                'SAN JUAN BAUTISTA CUICATLÁN',
                'SAN JUAN BAUTISTA GUELACHE',
                'SAN JUAN BAUTISTA JAYACATLÁN',
                'SAN JUAN BAUTISTA LO DE SOTO',
                'SAN JUAN BAUTISTA SUCHITEPEC',
                'SAN JUAN BAUTISTA TLACOATZINTEPEC',
                'SAN JUAN BAUTISTA TLACHICHILCO',
                'SAN JUAN BAUTISTA TUXTEPEC',
                'SAN JUAN CACATEPEC',
                'SAN JUAN CHICOMEZÚCHIL',
                'SAN JUAN CHILATECA',
                'SAN JUAN CIENEGUILLA',
                'SAN JUAN COATZÓSPAM',
                'SAN JUAN COLORADO',
                'SAN JUAN COMALTEPEC',
                'SAN JUAN COTZOCÓN',
                'SAN JUAN DE LOS CUÉS',
                'SAN JUAN DEL ESTADO',
                'SAN JUAN DEL RÍO',
                'SAN JUAN DIUXI',
                'SAN JUAN EVANGELISTA ANALCO',
                'SAN JUAN GUELAVÍA',
                'SAN JUAN GUICHICOVI',
                'SAN JUAN IHUALTEPEC',
                'SAN JUAN JUQUILA MIXES',
                'SAN JUAN JUQUILA VIJANOS',
                'SAN JUAN LACHAO',
                'SAN JUAN LACHIGALLA',
                'SAN JUAN LAJARCIA',
                'SAN JUAN LALANA',
                'SAN JUAN MAZATLÁN',
                'SAN JUAN MIXTEPEC',
                'SAN JUAN MIXTEPEC - DISTRITO 08',
                'SAN JUAN MIXTEPEC - DISTRITO 26',
                'SAN JUAN ÑUMÍ',
                'SAN JUAN OZOLOTEPEC',
                'SAN JUAN PETLAPA',
                'SAN JUAN QUIAHIJE',
                'SAN JUAN QUIOTEPEC',
                'SAN JUAN SAYULTEPEC',
                'SAN JUAN TABÁ',
                'SAN JUAN TAMAZOLA',
                'SAN JUAN TEITA',
                'SAN JUAN TEITIPAC',
                'SAN JUAN TEPEUXILA',
                'SAN JUAN TEPOSCOLULA',
                'SAN JUAN YAEE',
                'SAN JUAN YATZONA',
                'SAN JUAN YUCUITA',
                'SAN JUANIXTLAHUACA',
                'SAN LORENZO',
                'SAN LORENZO ALBARRADAS',
                'SAN LORENZO CACAOTEPEC',
                'SAN LORENZO CUAUNECUILTITLA',
                'SAN LORENZO TEXMELÚCAN',
                'SAN LORENZO VICTORIA',
                'SAN LUCAS CAMOTLÁN',
                'SAN LUCAS OJITLÁN',
                'SAN LUCAS QUIAVINÍ',
                'SAN LUCAS ZOQUIAPAM',
                'SAN LUIS AMATLÁN',
                'SAN MARCIAL OZOLOTEPEC',
                'SAN MARCOS ARTEAGA',
                'SAN MARTÍN DE LOS CANSECOS',
                'SAN MARTÍN HUAMELÚLPAM',
                'SAN MARTÍN ITUNYOSO',
                'SAN MARTÍN LACHILÁ',
                'SAN MARTÍN PERAS',
                'SAN MARTÍN TILCAJETE',
                'SAN MARTÍN TOXPALAN',
                'SAN MARTÍN ZACATEPEC',
                'SAN MATEO CAJONOS',
                'SAN MATEO DEL MAR',
                'SAN MATEO ETLATONGO',
                'SAN MATEO NEJÁPAM',
                'SAN MATEO PEÑASCO',
                'SAN MATEO PIÑAS',
                'SAN MATEO RÍO HONDO',
                'SAN MATEO SINDIHUI',
                'SAN MATEO TLAPILTEPEC',
                'SAN MATEO YOLOXOCHITLÁN',
                'SAN MELCHOR BETAZA',
                'SAN MIGUEL ACHIUTLA',
                'SAN MIGUEL AHUEHUETITLÁN',
                'SAN MIGUEL ALOÁPAM',
                'SAN MIGUEL AMATITLÁN',
                'SAN MIGUEL AMATLÁN',
                'SAN MIGUEL COATLÁN',
                'SAN MIGUEL CHICAHUA',
                'SAN MIGUEL CHIMALAPA',
                'SAN MIGUEL DEL PUERTO',
                'SAN MIGUEL DEL RÍO',
                'SAN MIGUEL EJUTLA',
                'SAN MIGUEL EL GRANDE',
                'SAN MIGUEL HUAUTLA',
                'SAN MIGUEL MIXTEPEC',
                'SAN MIGUEL PANIXTLAHUACA',
                'SAN MIGUEL PERAS',
                'SAN MIGUEL PIEDRAS',
                'SAN MIGUEL QUETZALTEPEC',
                'SAN MIGUEL SANTA FLOR',
                'SAN MIGUEL SOYALTEPEC',
                'SAN MIGUEL SUCHIXTEPEC',
                'SAN MIGUEL TECOMATLÁN',
                'SAN MIGUEL TENANGO',
                'SAN MIGUEL TEQUIXTEPEC',
                'SAN MIGUEL TILQUIÁPAM',
                'SAN MIGUEL TLACAMAMA',
                'SAN MIGUEL TLACOTEPEC',
                'SAN MIGUEL TULANCINGO',
                'SAN MIGUEL YOTAO',
                'SAN NICOLÁS',
                'SAN NICOLÁS HIDALGO',
                'SAN PABLO COATLÁN',
                'SAN PABLO CUATRO VENADOS',
                'SAN PABLO ETLA',
                'SAN PABLO HUITZO',
                'SAN PABLO HUIXTEPEC',
                'SAN PABLO MACUILTIANGUIS',
                'SAN PABLO TIJALTEPEC',
                'SAN PABLO VILLA DE MITLA',
                'SAN PABLO YAGANIZA',
                'SAN PEDRO AMUZGOS',
                'SAN PEDRO APÓSTOL',
                'SAN PEDRO ATOYAC',
                'SAN PEDRO CAJONOS',
                'SAN PEDRO COMITANCILLO',
                'SAN PEDRO COXCALTEPEC CÁNTAROS',
                'SAN PEDRO EL ALTO',
                'SAN PEDRO HUAMELULA',
                'SAN PEDRO HUILOTEPEC',
                'SAN PEDRO IXCATLÁN',
                'SAN PEDRO IXTLAHUACA',
                'SAN PEDRO JALTEPETONGO',
                'SAN PEDRO JICAYÁN',
                'SAN PEDRO JOCOTIPAC',
                'SAN PEDRO JUCHATENGO',
                'SAN PEDRO MÁRTIR',
                'SAN PEDRO MÁRTIR QUIECHAPA',
                'SAN PEDRO MÁRTIR YUCUXACO',
                'SAN PEDRO MIXTEPEC',
                'SAN PEDRO MIXTEPEC - DISTRITO 22',
                'SAN PEDRO MIXTEPEC - DISTRITO 26',
                'SAN PEDRO MOLINOS',
                'SAN PEDRO NOPALA',
                'SAN PEDRO OCOPETATILLO',
                'SAN PEDRO OCOTEPEC',
                'SAN PEDRO POCHUTLA',
                'SAN PEDRO QUIATONI',
                'SAN PEDRO SOCHIÁPAM',
                'SAN PEDRO TAPANATEPEC',
                'SAN PEDRO TAVICHE',
                'SAN PEDRO TEOZACOALCO',
                'SAN PEDRO TEUTILA',
                'SAN PEDRO TIDAA',
                'SAN PEDRO TOPILTEPEC',
                'SAN PEDRO TOTOLÁPAM',
                'SAN PEDRO Y SAN PABLO AYUTLA',
                'SAN PEDRO Y SAN PABLO TEPOSCOLULA',
                'SAN PEDRO Y SAN PABLO TEQUIXTEPEC',
                'SAN PEDRO YANERI',
                'SAN PEDRO YÓLOX',
                'SAN PEDRO YUCUNAMA',
                'SAN RAYMUNDO JALPAN',
                'SAN SEBASTIÁN ABASOLO',
                'SAN SEBASTIÁN COATLÁN',
                'SAN SEBASTIÁN IXCAPA',
                'SAN SEBASTIÁN NICANANDUTA',
                'SAN SEBASTIÁN RÍO HONDO',
                'SAN SEBASTIÁN TECOMAXTLAHUACA',
                'SAN SEBASTIÁN TEITIPAC',
                'SAN SEBASTIÁN TUTLA',
                'SAN SIMÓN ALMOLONGAS',
                'SAN SIMÓN ZAHUATLÁN',
                'SANTA ANA',
                'SANTA ANA ATEIXTLAHUACA',
                'SANTA ANA CUAUHTÉMOC',
                'SANTA ANA DEL VALLE',
                'SANTA ANA TAVELA',
                'SANTA ANA TLAPACOYAN',
                'SANTA ANA YARENI',
                'SANTA ANA ZEGACHE',
                'SANTA CATARINA CUIXTLA',
                'SANTA CATARINA IXTEPEJI',
                'SANTA CATARINA JUQUILA',
                'SANTA CATARINA LACHATAO',
                'SANTA CATARINA LOXICHA',
                'SANTA CATARINA MECHOACÁN',
                'SANTA CATARINA MINAS',
                'SANTA CATARINA QUIANÉ',
                'SANTA CATARINA QUIOQUITANI',
                'SANTA CATARINA TAYATA',
                'SANTA CATARINA TICUÁ',
                'SANTA CATARINA YOSONOTÚ',
                'SANTA CATARINA ZAPOQUILA',
                'SANTA CRUZ ACATEPEC',
                'SANTA CRUZ AMILPAS',
                'SANTA CRUZ DE BRAVO',
                'SANTA CRUZ ITUNDUJIA',
                'SANTA CRUZ MIXTEPEC',
                'SANTA CRUZ NUNDACO',
                'SANTA CRUZ PAPALUTLA',
                'SANTA CRUZ TACACHE DE MINA',
                'SANTA CRUZ TACAHUA',
                'SANTA CRUZ TAYATA',
                'SANTA CRUZ XITLA',
                'SANTA CRUZ XOXOCOTLÁN',
                'SANTA CRUZ ZENZONTEPEC',
                'SANTA GERTRUDIS',
                'SANTA INÉS DEL MONTE',
                'SANTA INÉS YATZECHE',
                'SANTA LUCÍA DEL CAMINO',
                'SANTA LUCÍA MIAHUATLÁN',
                'SANTA LUCÍA MONTEVERDE',
                'SANTA LUCÍA OCOTLÁN',
                'SANTA MAGDALENA JICOTLÁN',
                'SANTA MARÍA ALOTEPEC',
                'SANTA MARÍA APAZCO',
                'SANTA MARÍA ATZOMPA',
                'SANTA MARÍA CAMOTLÁN',
                'SANTA MARÍA CHACHOÁPAM',
                'SANTA MARÍA CHILCHOTLA',
                'SANTA MARÍA CHIMALAPA',
                'SANTA MARÍA COLOTEPEC',
                'SANTA MARÍA CORTIJO',
                'SANTA MARÍA COYOTEPEC',
                'SANTA MARÍA DEL ROSARIO',
                'SANTA MARÍA DEL TULE',
                'SANTA MARÍA ECATEPEC',
                'SANTA MARÍA GUELACÉ',
                'SANTA MARÍA GUIENAGATI',
                'SANTA MARÍA HUATULCO',
                'SANTA MARÍA HUAZOLOTITLÁN',
                'SANTA MARÍA IPALAPA',
                'SANTA MARÍA IXCATLÁN',
                'SANTA MARÍA JACATEPEC',
                'SANTA MARÍA JALAPA DEL MARQUÉS',
                'SANTA MARÍA JALTIANGUIS',
                'SANTA MARÍA LA ASUNCIÓN',
                'SANTA MARÍA LACHIXÍO',
                'SANTA MARÍA MIXTEQUILLA',
                'SANTA MARÍA NATIVITAS',
                'SANTA MARÍA NDUAYACO',
                'SANTA MARÍA OZOLOTEPEC',
                'SANTA MARÍA PÁPALO',
                'SANTA MARÍA PEÑOLES',
                'SANTA MARÍA PETAPA',
                'SANTA MARÍA QUIEGOLANI',
                'SANTA MARÍA SOLA',
                'SANTA MARÍA TATALTEPEC',
                'SANTA MARÍA TECOMAVACA',
                'SANTA MARÍA TEMAXCALTEPEC',
                'SANTA MARÍA TEPANTLALI',
                'SANTA MARÍA TEXCATITLÁN',
                'SANTA MARÍA TLAHUITOLTEPEC',
                'SANTA MARÍA TLALIXTAC',
                'SANTA MARÍA TONAMECA',
                'SANTA MARÍA TOTOLAPILLA',
                'SANTA MARÍA XADANI',
                'SANTA MARÍA YALINA',
                'SANTA MARÍA YAVESÍA',
                'SANTA MARÍA YOLOTEPEC',
                'SANTA MARÍA YOSOYÚA',
                'SANTA MARÍA YUCUHITI',
                'SANTA MARÍA ZACATEPEC',
                'SANTA MARÍA ZANIZA',
                'SANTA MARÍA ZOQUITLÁN',
                'SANTIAGO AMOLTEPEC',
                'SANTIAGO APOALA',
                'SANTIAGO APÓSTOL',
                'SANTIAGO ASTATA',
                'SANTIAGO ATITLÁN',
                'SANTIAGO AYUQUILILLA',
                'SANTIAGO CACALOXTEPEC',
                'SANTIAGO CAMOTLÁN',
                'SANTIAGO CHAZUMBA',
                'SANTIAGO CHOÁPAM',
                'SANTIAGO COMALTEPEC',
                'SANTIAGO DEL RÍO',
                'SANTIAGO HUAJOLOTITLÁN',
                'SANTIAGO HUAUCLILLA',
                'SANTIAGO IHUITLÁN PLUMAS',
                'SANTIAGO IXCUINTEPEC',
                'SANTIAGO IXTAYUTLA',
                'SANTIAGO JAMILTEPEC',
                'SANTIAGO JOCOTEPEC',
                'SANTIAGO JUXTLAHUACA',
                'SANTIAGO LACHIGUIRI',
                'SANTIAGO LALOPA',
                'SANTIAGO LAOLLAGA',
                'SANTIAGO LAXOPA',
                'SANTIAGO LLANO GRANDE',
                'SANTIAGO MATATLÁN',
                'SANTIAGO MILTEPEC',
                'SANTIAGO MINAS',
                'SANTIAGO NACALTEPEC',
                'SANTIAGO NEJAPILLA',
                'SANTIAGO NILTEPEC',
                'SANTIAGO NUNDICHE',
                'SANTIAGO NUYOÓ',
                'SANTIAGO PINOTEPA NACIONAL',
                'SANTIAGO SUCHILQUITONGO',
                'SANTIAGO TAMAZOLA',
                'SANTIAGO TAPEXTLA',
                'SANTIAGO TENANGO',
                'SANTIAGO TEPETLAPA',
                'SANTIAGO TETEPEC',
                'SANTIAGO TEXCALCINGO',
                'SANTIAGO TEXTITLÁN',
                'SANTIAGO TILANTONGO',
                'SANTIAGO TILLO',
                'SANTIAGO TLAZOYALTEPEC',
                'SANTIAGO XANICA',
                'SANTIAGO XIACUÍ',
                'SANTIAGO YAITEPEC',
                'SANTIAGO YAVEO',
                'SANTIAGO YOLOMÉCATL',
                'SANTIAGO YOSONDÚA',
                'SANTIAGO YUCUYACHI',
                'SANTIAGO ZACATEPEC',
                'SANTIAGO ZOOCHILA',
                'SANTO DOMINGO ALBARRADAS',
                'SANTO DOMINGO ARMENTA',
                'SANTO DOMINGO CHIHUITÁN',
                'SANTO DOMINGO DE MORELOS',
                'SANTO DOMINGO INGENIO',
                'SANTO DOMINGO IXCATLÁN',
                'SANTO DOMINGO NUXAÁ',
                'SANTO DOMINGO OZOLOTEPEC',
                'SANTO DOMINGO PETAPA',
                'SANTO DOMINGO ROAYAGA',
                'SANTO DOMINGO TEHUANTEPEC',
                'SANTO DOMINGO TEOJOMULCO',
                'SANTO DOMINGO TEPUXTEPEC',
                'SANTO DOMINGO TOMALTEPEC',
                'SANTO DOMINGO TONALÁ',
                'SANTO DOMINGO TONALTEPEC',
                'SANTO DOMINGO XAGACÍA',
                'SANTO DOMINGO YANHUITLÁN',
                'SANTO DOMINGO YODOHINO',
                'SANTO DOMINGO ZANATEPEC',
                'SANTO TOMÁS JALIEZA',
                'SANTO TOMÁS MAZALTEPEC',
                'SANTO TOMÁS OCOTEPEC',
                'SANTO TOMÁS TAMAZULAPAN',
                'SANTOS REYES NOPALA',
                'SANTOS REYES PÁPALO',
                'SANTOS REYES TEPEJILLO',
                'SANTOS REYES YUCUNÁ',
                'SILACAYOÁPAM',
                'SITIO DE XITLAPEHUA',
                'SOLEDAD ETLA',
                'TAMAZULÁPAM DEL ESPÍRITU SANTO',
                'TANETZE DE ZARAGOZA',
                'TANICHE',
                'TATALTEPEC DE VALDÉS',
                'TEOCOCUILCO DE MARCOS PÉREZ',
                'TEOTITLÁN DE FLORES MAGÓN',
                'TEOTITLÁN DEL VALLE',
                'TEOTONGO',
                'TEPELMEME VILLA DE MORELOS',
                'TEZOATLÁN DE SEGURA Y LUNA',
                'TLACOLULA DE MATAMOROS',
                'TLACOTEPEC DE BENITO JUÁREZ',
                'TLALIXTAC DE CABRERA',
                'TOTONTEPEC VILLA DE MORELOS',
                'TRINIDAD ZAACHILA',
                'TRINIDAD ZOCHIMILCO',
                'UNIÓN HIDALGO',
                'VALERIO TRUJANO',
                'VILLA DE CHILAPA DE DÍAZ',
                'VILLA DE ETLA',
                'VILLA DE TAMAZULÁPAM DEL PROGRESO',
                'VILLA DE TUTUTEPEC',
                'VILLA DE ZAACHILA',
                'VILLA DÍAZ ORDAZ',
                'VILLA HIDALGO',
                'VILLA SOLA DE VEGA',
                'VILLA TALEA DE CASTRO',
                'VILLA TEJÚPAM DE LA UNIÓN',
                'YAXE',
                'YOGANA',
                'YUTANDUCHI DE GUERRERO',
                'ZAPOTITLÁN LAGUNAS',
                'ZAPOTITLÁN PALMAS',
                'ZIMATLÁN DE ÁLVAREZ'
            ],
            12 => [
                'ACAPULCO DE JUÁREZ',
                'ACATEPEC',
                'AHUACUOTZINGO',
                'AJUCHITLÁN DEL PROGRESO',
                'ALCOZAUCA DE GUERRERO',
                'ALPOYECA',
                'APAXTLA',
                'ARCELIA',
                'ATENANGO DEL RÍO',
                'ATLAMAJALCINGO DEL MONTE',
                'ATLIXTAC',
                'ATOYAC DE ÁLVAREZ',
                'AYUTLA DE LOS LIBRES',
                'AZOYÚ',
                'BENITO JUÁREZ',
                'BUENAVISTA DE CUÉLLAR',
                'COAHUAYUTLA DE JOSÉ MARÍA IZAZAGA',
                'COCULA',
                'COPALA',
                'COPALILLO',
                'COPANATOYAC',
                'COYUCA DE BENÍTEZ',
                'COYUCA DE CATALÁN',
                'CUAJINICUILAPA',
                'CUALÁC',
                'CUAUTEPEC',
                'CUETZALA DEL PROGRESO',
                'CUTZAMALA DE PINZÓN',
                'CHILAPA DE ÁLVAREZ',
                'CHILPANCINGO DE LOS BRAVO',
                'FLORENCIO VILLARREAL',
                'GENERAL CANUTO A. NERI',
                'GENERAL HELIODORO CASTILLO',
                'HUAMUXTITLÁN',
                'HUITZUCO DE LOS FIGUEROA',
                'IGUALA DE LA INDEPENDENCIA',
                'IGUALAPA',
                'ILLIATENCO',
                'IXCATEOPAN DE CUAUHTÉMOC',
                'JOSÉ JOAQUÍN DE HERRERA',
                'JUAN R. ESCUDERO',
                'JUCHITÁN',
                'LA UNIÓN DE ISIDORO MONTES DE OCA',
                'LEONARDO BRAVO',
                'MALINALTEPEC',
                'MÁRTIR DE CUILAPAN',
                'METLATÓNOC',
                'MOCHITLÁN',
                'OLINALÁ',
                'OMETEPEC',
                'PEDRO ASCENCIO ALQUISIRAS',
                'PETATLÁN',
                'PILCAYA',
                'PUNGARABATO',
                'QUECHULTENANGO',
                'SAN LUIS ACATLÁN',
                'SAN MARCOS',
                'SAN MIGUEL TOTOLAPAN',
                'TAXCO DE ALARCÓN',
                'TECOANAPA',
                'TÉCPAN DE GALEANA',
                'TELOLOAPAN',
                'TEPECOACUILCO DE TRUJANO',
                'TETIPAC',
                'TIXTLA DE GUERRERO',
                'TLACOACHISTLAHUACA',
                'TLACOAPA',
                'TLALCHAPA',
                'TLALCOLOTLIPA',
                'TLALIAXACA',
                'TLAPA DE COMONFORT',
                'TLAPEHUALA',
                'XALPATLÁHUAC',
                'XOCHIHUEHUETLÁN',
                'XOCHISTLAHUACA',
                'ZAPOTITLÁN TABLAS',
                'ZIRÁNDARO',
                'ZITLALA'
            ],
            21 => [
                'ACAJETE',
                'ACATENO',
                'ACATLÁN',
                'ACATZINGO',
                'ACTEOPAN',
                'AHUACATLÁN',
                'AHUATLÁN',
                'AHUAZOTEPEC',
                'AHUEHUETITLA',
                'AJALPAN',
                'ALBINO ZERTUCHE',
                'ALJOJUCA',
                'ALTEPEXI',
                'AMIXTLÁN',
                'AMOZOC',
                'AQUIXTLA',
                'ATEMPAN',
                'ATEXCAL',
                'ATLIXCO',
                'ATOYATEMPAN',
                'ATZALA',
                'ATZITZIHUACÁN',
                'ATZITZINTLA',
                'AXUTLA',
                'AYOTOXCO DE GUERRERO',
                'CALPAN',
                'CALTEPEC',
                'CAMOCUAUTLA',
                'CAÑADA MORELOS',
                'CAXHUACÁN',
                'COATEPEC',
                'COATZINGO',
                'COHETZALA',
                'COHUECAN',
                'CORONANGO',
                'COXCATLÁN',
                'COYOMEAPAN',
                'COYOTEPEC',
                'CUAPIAXTLA DE MADERO',
                'CUAUTEMPAN',
                'CUAUTINCHÁN',
                'CUAUTLANCINGO',
                'CUAYUCA DE ANDRADE',
                'CUETZALAN DEL PROGRESO',
                'CUYOACO',
                'CHALCHICOMULA DE SESMA',
                'CHAPULCO',
                'CHIAUTLA',
                'CHIAUTZINGO',
                'CHICONCUAUTLA',
                'CHICHIQUILA',
                'CHIETLA',
                'CHIGMECATITLÁN',
                'CHIGNAHUAPAN',
                'CHIGNAUTLA',
                'CHILA',
                'CHILA DE LA SAL',
                'HONEY',
                'CHILCHOTLA',
                'CHINANTLA',
                'DOMINGO ARENAS',
                'ELOXOCHITLÁN',
                'EPATLÁN',
                'ESPERANZA',
                'FRANCISCO Z. MENA',
                'GENERAL FELIPE ÁNGELES',
                'GUADALUPE',
                'GUADALUPE VICTORIA',
                'HERMENEGILDO GALEANA',
                'HUAQUECHULA',
                'HUATLATLAUCA',
                'HUAUCHINANGO',
                'HUEHUETLA',
                'HUEHUETLÁN EL CHICO',
                'HUEHUETLÁN EL GRANDE',
                'HUEJOTZINGO',
                'HUEYAPAN',
                'HUEYTAMALCO',
                'HUEYTLALPAN',
                'HUITZILÁN DE SERDÁN',
                'HUITZILTEPEC',
                'IXCAMILPA DE GUERRERO',
                'IXCAQUIXTLA',
                'IXTACAMAXTITLÁN',
                'IXTEPEC',
                'IZÚCAR DE MATAMOROS',
                'JALPAN',
                'JOLALPAN',
                'JONOTLA',
                'JOPALA',
                'JUAN C. BONILLA',
                'JUAN GALINDO',
                'JUAN N. MÉNDEZ',
                'LAFRAGUA',
                'LIBRES',
                'LA MAGDALENA TLATLAUQUITEPEC',
                'MAZAPILTEPEC DE JUÁREZ',
                'MIXTLA',
                'MOLCAXAC',
                'NAUPAN',
                'NAUZONTLA',
                'NEALTICÁN',
                'NÍCOLAS BRAVO',
                'NOPALUCAN',
                'OCOTEPEC',
                'OCOYUCAN',
                'OLINTLA',
                'ORIENTAL',
                'PAHUATLÁN',
                'PALMAR DE BRAVO',
                'PANTEPEC',
                'PETLALCINGO',
                'PIAXTLA',
                'PUEBLA',
                'QUECHOLAC',
                'QUIMIXTLÁN',
                'RAFAEL LARA GRAJALES',
                'LOS REYES DE JUÁREZ',
                'SAN ANDRÉS CHOLULA',
                'SAN ANTONIO CAÑADA',
                'SAN DIEGO LA MESA TOCHIMILTZINGO',
                'SAN FELIPE TEOTLALCINGO',
                'SAN FELIPE TEPATLAN',
                'SAN GABRIEL CHILAC',
                'SAN GREGORIO ATZOMPA',
                'SAN JERÓNIMO TECUANIPAN',
                'SAN JERÓNIMO XAYACATLÁN',
                'SAN JOSÉ CHIAPA',
                'SAN JOSÉ MIAHUATLÁN',
                'SAN JUAN ATENCO',
                'SAN JUAN ATZOMPA',
                'SAN MARTÍN TEXMELUCAN',
                'SAN MARTÍN TOTOLTEPEC',
                'SAN MATÍAS TLALANCALECA',
                'SAN MIGUEL IXITLÁN',
                'SAN MIGUEL XOXTLA',
                'SAN NICOLÁS BUENOS AIRES',
                'SAN NICOLÁS DE LOS RANCHOS',
                'SAN PABLO ANICANO',
                'SAN PEDRO CHOLULA',
                'SAN PEDRO YELOIXTLAHUACA',
                'SAN SALVADOR EL SECO',
                'SAN SALVADOR EL VERDE',
                'SAN SALVADOR HUIXCOLOTLA',
                'SANTA CATARINA TLALTEMPAN',
                'SANTA INÉS AHUATEMPAN',
                'SANTA ISABEL CHOLULA',
                'SANTIAGO MIAHUATLÁN',
                'SANTO TOMÁS HUEYOTLIPAN',
                'SOLTEPEC',
                'TECALI DE HERRERA',
                'TECAMACHALCO',
                'TECOMATLÁN',
                'TEHUACÁN',
                'TEHUITZINGO',
                'TENAMPULCO',
                'TEOPANTLAN',
                'TEOTLALCO',
                'TEPANCO DE LÓPEZ',
                'TEPANGO DE RODRÍGUEZ',
                'TEPATLAXCO DE HIDALGO',
                'TEPEACA',
                'TEPEMAXALCO',
                'TEPEOJUMA',
                'TEPETZINTLA',
                'TEPEXCO',
                'TEPEXI DE RODRÍGUEZ',
                'TEPEYAHUALCO',
                'TEPEYAHUALCO DE CUAUHTÉMOC',
                'TETELA DE OCAMPO',
                'TETELES DE ÁVILA CASTILLO',
                'TEZIUTLÁN',
                'TIANGUISMANALCO',
                'TILAPA',
                'TLACOTEPEC DE BENITO JUÁREZ',
                'SAN SEBASTIÁN TLACOTEPEC',
                'TLACUILOTEPEC',
                'TLACHICHUCA',
                'TLAHUAPAN',
                'TLALTENANGO',
                'TLANEPANTLA',
                'TLAOLA',
                'TLAPACOYA',
                'TLAPANALA',
                'TLATLAUQUITEPEC',
                'TLAXCO',
                'TOCHIMILCO',
                'TOCHTEPEC',
                'TOTOLTEPEC DE GUERRERO',
                'TULCINGO',
                'TUZAMAPÁN DE GALEANA',
                'TZICATLACOYAN',
                'VENUSTIANO CARRANZA',
                'VICENTE GUERRERO',
                'XAYACATLÁN DE BRAVO',
                'XICOTEPEC',
                'XICOTLÁN',
                'XIUTETELCO',
                'XOCHIAPULCO',
                'XOCHILTEPEC',
                'XOCHITLÁN DE VICENTE SUÁREZ',
                'XOCHITLÁN TODOS SANTOS',
                'YAONAHUAC',
                'YEHUALTEPEC',
                'ZACAPALA',
                'ZACAPOAXTLA',
                'ZACATLÁN',
                'ZAPOTITLÁN',
                'ZAPOTITLÁN DE MÉNDEZ',
                'ZARAGOZA',
                'ZAUTLA',
                'ZIHUATEUTLA'
            ],
            17 => [
                'AMACUZAC',
                'ATLATLAHUCAN',
                'AXOCHIAPAN',
                'AYALA',
                'COATLÁN DEL RÍO',
                'COAUTLA',
                'CUERNAVACA',
                'EMILIANO ZAPATA',
                'HUITZILAC',
                'JANTETELCO',
                'JIUTEPEC',
                'JOJUTLA',
                'JONACATEPEC',
                'MAZATEPEC',
                'MIACATLÁN',
                'OCUITUCO',
                'PUENTE DE IXTLA',
                'TEMIXCO',
                'TEPALCINGO',
                'TEPOZTLÁN',
                'TETECALA',
                'TETELA DEL VOLCÁN',
                'TLAYACAPAN',
                'TLALTIZAPÁN',
                'TLALNEPANTLA',
                'TOTOLAPAN',
                'XOCHITEPEC',
                'XOXOCOTLA',
                'YAUTEPEC',
                'YECAPIXTLA',
                'ZACATEPEC',
                'ZACUALPAN DE AMILPAS'
            ],
            29 => [
                'ACUAMANALA DE MIGUEL HIDALGO',
                'ALTZAYANCA',
                'AMAXAC DE GUERRERO',
                'APETATITLÁN DE ANTONIO CARVAJAL',
                'APIZACO',
                'ATLANGATEPEC',
                'ATLTZAYANCA',
                'BENITO JUÁREZ',
                'CALPULALPAN',
                'CHIAUTEMPAN',
                'CONTLA DE JUAN CUAMATZI',
                'CUAPIAXTLA',
                'CUAXOMULCO',
                'EL CARMEN TEQUEXQUITLA',
                'EMILIANO ZAPATA',
                'ESPÁÑITA',
                'HUAMANTLA',
                'HUEYOTLIPAN',
                'IXTACUIXTLA DE MARIANO MATAMOROS',
                'IXTENCO',
                'LA MAGDALENA TLALTELULCO',
                'LAZARO CÁRDENAS',
                'MUÑOZ DE DOMINGO ARENAS',
                'NANACAMILPA DE MARIANO ARISTA',
                'NATIVITAS',
                'NIXTLAHUACÁN',
                'PANOTLA',
                'PAPALOTLA DE XICOHTÉNCATL',
                'PETLALCINGO',
                'PUEBLA DE GUADALUPE',
                'PUXTEC',
                'SAN DAMIÁN TEXOLOC',
                'SAN FELIPE TLAXCALA',
                'SAN JERÓNIMO ZILTENCO',
                'SAN LUCAS TECOPILCO',
                'SAN PABLO DEL MONTE',
                'SANTA ANA NOPALUCAN',
                'SANTA APOLONIA TEACALCO',
                'SANTA CRUZ TLAXCALA',
                'SANTA ISABEL XILOXOXTLA',
                'SANTA MAGDALENA TLALTELULCO',
                'SANTA MARÍA TEZONTEPEC',
                'SANTA TERESA',
                'SANTIAGO MUYUMBA',
                'SANTO TOMÁS',
                'TENANCINGO',
                'TEOLOYUCAN',
                'TEPETITLA DE LARDIZÁBAL',
                'TEPEYANCO',
                'TEQUIXQUIAC',
                'TETLA DE LA SOLIDARIDAD',
                'TETLATLA',
                'TLAXCALA',
                'TOTOLAC',
                'TULANCINGO',
                'TULTEPEC',
                'TZOMPANTEPEC',
                'XALOZTOC',
                'XALTIANCO',
                'XOCHIATIPAN',
                'XOCHITEPEC',
                'YAUHQUEMEHCAN',
                'ZACAPOAXTLA',
                'ZACATLÁN',
                'ZOMATLÁN',
                'ZOTOLUCA'
            ],
            15 => [
                'ACAMBAY',
                'ACOLMAN',
                'ACULCO',
                'ALMOLOYA DE ALQUISIRAS',
                'ALMOLOYA DE JUÁREZ',
                'ALMOLOYA DEL RÍO',
                'AMANALCO',
                'AMATEPEC',
                'AMECAMECA',
                'APAXCO',
                'ATENCO',
                'ATIZAPÁN',
                'ATIZAPÁN DE ZARAGOZA',
                'ATLACOMULCO',
                'ATLAUTLA',
                'AXAPUSCO',
                'AYAPANGO',
                'CALIMAYA',
                'CAPULHUAC',
                'CHALCO',
                'CHAPA DE MOTA',
                'CHAPULTEPEC',
                'CHIAUTLA',
                'CHICOLOAPAN',
                'CHICONCUAC',
                'CHIMALHUACÁN',
                'COACALCO DE BERRIOZÁBAL',
                'COATEPEC HARINAS',
                'COCOTITLÁN',
                'COYOTEPEC',
                'CUAUTITLÁN',
                'CUAUTITLÁN IZCALLI',
                'DONATO GUERRA',
                'ECATEPEC DE MORELOS',
                'EL ORO',
                'HUEHUETOCA',
                'HUEYPOXTLA',
                'HUIXQUILUCAN',
                'ISIDRO FABELA',
                'IXTAPALUCA',
                'IXTAPAN DE LA SAL',
                'IXTAPAN DEL ORO',
                'IXTLAHUACA',
                'JALTENCO',
                'JILOTEPEC',
                'JILOTZINGO',
                'JIQUIPILCO',
                'JOCOTITLÁN',
                'JOQUICINGO',
                'JUCHITEPEC',
                'LA PAZ',
                'LERMA',
                'LUVIANOS',
                'MALINALCO',
                'MELCHOR OCAMPO',
                'METEPEC',
                'MEXICALTZINGO',
                'MORELOS',
                'NAUCALPAN DE JUÁREZ',
                'NEXTLALPAN',
                'NEZAHUALCÓYOTL',
                'NICOLÁS ROMERO',
                'NOPALTEPEC',
                'OCOYOACAC',
                'OCUILAN',
                'OTZOLOAPAN',
                'OTZOLOTEPEC',
                'OZUMBA',
                'PAPALOTLA',
                'POLOTITLÁN',
                'RAYÓN',
                'SAN ANTONIO LA ISLA',
                'SAN FELIPE DEL PROGRESO',
                'SAN JOSÉ DEL RINCÓN',
                'SAN MARTÍN DE LAS PIRÁMIDES',
                'SAN MATEO ATENCO',
                'SAN SIMÓN DE GUERRERO',
                'SANTO TOMÁS',
                'SOYANIQUILPAN DE JUÁREZ',
                'SULTEPEC',
                'TECÁMAC',
                'TEJUPILCO',
                'TEMAMATLA',
                'TEMASCALAPA',
                'TEMASCALCINGO',
                'TEMASCALTEPEC',
                'TEMOAYA',
                'TENANCINGO',
                'TENANGO DEL AIRE',
                'TENANGO DEL VALLE',
                'TEOLOYUCAN',
                'TEOTIHUACÁN',
                'TEPETLAOXTOC',
                'TEPETLIXPA',
                'TEPOTZOTLÁN',
                'TEQUIXQUIAC',
                'TEXCALTITLÁN',
                'TEXCALYACAC',
                'TEXCOCO',
                'TEZOYUCA',
                'TIANGUISTENCO',
                'TIMILPAN',
                'TLALMANALCO',
                'TLALNEPANTLA DE BAZ',
                'TLATLAYA',
                'TOLUCA',
                'TONANITLA',
                'TONATICO',
                'TULTEPEC',
                'TULTITLÁN',
                'VALLE DE BRAVO',
                'VALLE DE CHALCO SOLIDARIDAD',
                'VILLA DE ALLENDE',
                'VILLA DEL CARBÓN',
                'VILLA GUERRERO',
                'VILLA VICTORIA',
                'XALATLACO',
                'XONACATLÁN',
                'ZACAZONAPAN',
                'ZACUALPAN',
                'ZINACANTEPEC',
                'ZUMPAHUACÁN',
                'ZUMPANGO',
            ],
            9 => [
                'ÁLVARO OBREGÓN',
                'AZCAPOTZALCO',
                'BENITO JUÁREZ',
                'COYOACÁN',
                'CUAJIMALPA DE MORELOS',
                'CUAUHTÉMOC',
                'GUSTAVO A. MADERO',
                'IZTACALCO',
                'IZTAPALAPA',
                'LA MAGDALENA CONTRERAS',
                'MILPA ALTA',
                'ÁOCHIMILCO',
                'TLÁHUAC',
                'TLALPAN',
                'VENUSTIANO CARRANZA',
                'XOCHIMILCO',
            ],
            13 => [
                'ACATLÁN',
                'ACAXOCHITLÁN',
                'ACTOPAN',
                'AGUA BLANCA DE ITURBIDE',
                'AJACUBA',
                'ALFAJAYUCAN',
                'ALMOLOYA',
                'APAN',
                'ATITALAQUIA',
                'ATLAPEXCO',
                'ATOTONILCO DE TULA',
                'ATOTONILCO EL GRANDE',
                'CALNALI',
                'CARDONAL',
                'CHAPANTONGO',
                'CHAPULHUACÁN',
                'CHILCUAUTLA',
                'CUAUTEPEC DE HINOJOSA',
                'EL ARENAL',
                'EPAZOYUCAN',
                'FRANCISCO I. MADERO',
                'HUASCA DE OCAMPO',
                'HUAUTLA',
                'HUAZALINGO',
                'HUEHUETLA',
                'HUEJUTLA DE REYES',
                'HUICHAPAN',
                'IXMIQUILPAN',
                'JACALA DE LEDEZMA',
                'JALTOCÁN',
                'JUÁREZ HIDALGO',
                'LOLOTLA',
                'METEPEC',
                'METZTITLÁN',
                'MINERAL DE LA REFORMA',
                'MINERAL DEL CHICO',
                'MINERAL DEL MONTE',
                'MIXQUIAHUALA DE JUÁREZ',
                'MOLANGO DE ESCAMILLA',
                'NICOLÁS FLORES',
                'NOPALA DE VILLAGRÁN',
                'OMITLÁN DE JUÁREZ',
                'PACHUCA DE SOTO',
                'PACULA',
                'PISAFLORES',
                'PROGRESO DE OBREGÓN',
                'SAN AGUSTÍN TLAXIACA',
                'SAN AGUSTÍN METZQUITITLÁN',
                'SAN BARTOLO TUTOTEPEC',
                'SAN FELIPE ORIZATLÁN',
                'SAN SALVADOR',
                'SANTIAGO DE ANAYA',
                'SANTIAGO TULANTEPEC DE LUGO GUERRERO',
                'SINGUILUCAN',
                'TASQUILLO',
                'TECOZAUTLA',
                'TENANGO DE DORIA',
                'TEPEAPULCO',
                'TEPEHUACÁN DE GUERRERO',
                'TEPEJI DEL RÍO DE OCAMPO',
                'TEPETITLÁN',
                'TETEPANGO',
                'VILLA DE TEZONTEPEC',
                'TEZONTEPEC DE ALDAMA',
                'TIANGUISTENGO',
                'TIZAYUCA',
                'TLAHUELILPAN',
                'TLAHUILTEPA',
                'TLANALAPA',
                'TLANCHINOL',
                'TLAXCOAPAN',
                'TOLCAYUCA',
                'TULA DE ALLENDE',
                'TULANCINGO DE BRAVO',
                'XOCHIATIPAN',
                'XOCHICOATLÁN',
                'YAHUALICA',
                'ZACUALTIPÁN DE ÁNGELES',
                'ZAPOTLÁN DE JUÁREZ',
                'ZEMPOALA',
                'ZIMAPÁN'
            ],
            16 => [
                'ACUITZIO',
                'AGUILILLA',
                'ÁLVARO OBREGÓN',
                'ANGAMACUTIRO',
                'ANGANGUEO',
                'APATZINGÁN',
                'APORO',
                'AQUILA',
                'ARIO',
                'ARTEAGA',
                'BRISEÑAS',
                'BUENAVISTA',
                'CARÁCUARO',
                'CHARAPAN',
                'CHARO',
                'CHAVINDA',
                'CHERÁN',
                'CHILCHOTA',
                'CHINICUILA',
                'CHUCÁNDIRO',
                'CHURINTZIO',
                'CHURUMUCO',
                'COAHUAYANA',
                'COALCOMÁN',
                'COENEO',
                'COJUMATLÁN DE RÉGULES',
                'CONTEPEC',
                'COPÁNDARO',
                'COTIJA',
                'CUITZEO',
                'ECUANDUREO',
                'EPITACIO HUERTA',
                'ERONGARÍCUARO',
                'GABRIEL ZAMORA',
                'HIDALGO',
                'HUACANA',
                'HUANDACAREO',
                'HUANIQUEO',
                'HUETAMO',
                'HUIRAMBA',
                'INDAPARAPEO',
                'IRIMBO',
                'IXTLÁN',
                'JACONA',
                'JIMÉNEZ',
                'JIQUILPAN',
                'JUÁREZ',
                'JUNGAPEO',
                'LAGUNILLAS',
                'LAZARO CÁRDENAS',
                'LOS REYES',
                'MADERO',
                'MARAVATÍO',
                'MARCOS CASTELLANOS',
                'MORELIA',
                'MORELOS',
                'MÚGICA',
                'NAHUATZEN',
                'NOCUPÉTARO',
                'NUEVO PARANGARICUTIRO',
                'NUEVO URECHO',
                'NUMARÁN',
                'OCAMPO',
                'PAJACUARAN',
                'PANINDÍCUARO',
                'PARÁCUARO',
                'PARACHO',
                'PÁTZCUARO',
                'PENJAMILLO',
                'PERIBÁN',
                'PURÉPERO',
                'PURUÁNDIRO',
                'QUERÉNDARO',
                'QUIROGA',
                'COJUMATLÁN DE RÉGULES',
                'SÁHUAYO',
                'SALVADOR ESCALANTE',
                'SAN LUCAS',
                'SANTA ANA MAYA',
                'SENGUIO',
                'SUSUPUATO',
                'TACÁMBARO',
                'TANCÍTARO',
                'TANGAMANDAPIO',
                'TANGANCÍCUARO',
                'TANHUATO',
                'TARETAN',
                'TARÍMBARO',
                'TEPALCATEPEC',
                'TINGAMBATO',
                'TINGÜINDÍN',
                'TIQUICHEO DE NICOLÁS ROMERO',
                'TLALPUJAHUA',
                'TLAZAZALCA',
                'TOCUMBO',
                'TUMBISCATÍO',
                'TURICATO',
                'TUXPAN',
                'TUZANTLA',
                'TZINTZUNTZAN',
                'TZITZIO',
                'URUAPAN',
                'VENUSTIANO CARRANZA',
                'VILLAMAR',
                'VISTA HERMOSA',
                'YURÉCUARO',
                'ZACAPU',
                'ZAMORA',
                'ZINÁPARO',
                'ZINAPÉCUARO',
                'ZIRACUARO',
                'ZITÁCUARO',
            ],
            11 => [
                'ABASOLO',
                'ACÁMBARO',
                'APASEO EL ALTO',
                'APASEO EL GRANDE',
                'ATARJEA',
                'CELAYA',
                'COMONFORT',
                'CORONEO',
                'CORTAZAR',
                'CUERÁMARO',
                'DOCTOR MORA',
                'DOLORES HIDALGO CUNA DE LA INDEPENDENCIA NACIONAL',
                'GUANAJUATO',
                'HUANÍMARO',
                'IRAPUATO',
                'JARAL DEL PROGRESO',
                'JERÉCUARO',
                'LEÓN',
                'MANUEL DOBLADO',
                'MOROLEÓN',
                'OCAMPO',
                'PÉNJAMO',
                'PUEBLO NUEVO',
                'PURÍSIMA DEL RINCÓN',
                'ROMITA',
                'SALAMANCA',
                'SALVATIERRA',
                'SAN DIEGO DE LA UNIÓN',
                'SAN FELIPE',
                'SAN FRANCISCO DEL RINCÓN',
                'SAN JOSÉ ITURBIDE',
                'SAN LUIS DE LA PAZ',
                'SAN MIGUEL DE ALLENDE',
                'SANTA CATARINA',
                'SANTA CRUZ DE JUVENTINO ROSAS',
                'SANTIAGO MARAVATÍO',
                'SILAO DE LA VICTORIA',
                'TARANDACUAO',
                'TARIMORO',
                'TIERRA BLANCA',
                'URIANGATO',
                'VALLE DE SANTIAGO',
                'VICTORIA',
                'VILLAGRÁN',
                'XICHÚ',
                'YURIRIA'
            ],
            22 => [
                'AMEALCO DE BONFIL',
                'ARROYO SECO',
                'CADEREYTA DE MONTES',
                'COLÓN',
                'CORREGIDORA',
                'EL MARQUÉS',
                'EZEQUIEL MONTES',
                'HUIMILPAN',
                'JALPAN DE SERRA',
                'LANDA DE MATAMOROS',
                'PEDRO ESCOBEDO',
                'PEÑAMILLER',
                'PINAL DE AMOLES',
                'QUERÉTARO',
                'SAN JOAQUÍN',
                'SAN JUAN DEL RÍO',
                'TEQUISQUIAPAN',
                'TOLIMÁN',
            ],
            24 => [
                'AHUALULCO',
                'ALAQUINES',
                'AQUISMÓN',
                'ARMADILLO DE LOS INFANTE',
                'AXTLA DE TERRAZAS',
                'CÁRDENAS',
                'CATORCE',
                'CEDRAL',
                'CERRITOS',
                'CERRO DE SAN PEDRO',
                'CIUDAD DEL MAÍZ',
                'CIUDAD FERNÁNDEZ',
                'CIUDAD VALLES',
                'COXCATLÁN',
                'CHARCAS',
                'EBANO',
                'EL NARANJO',
                'GUADALCÁZAR',
                'HUEHUETLÁN',
                'LAGUNILLAS',
                'MATEHUALA',
                'MEXQUITIC DE CARMONA',
                'MOCTEZUMA',
                'RAYÓN',
                'RIOVERDE',
                'SALINAS',
                'SAN ANTONIO',
                'SAN CIRO DE ACOSTA',
                'SAN LUIS POTOSÍ',
                'SAN MARTÍN CHALCHICUAUTLA',
                'SAN NICOLÁS TOLENTINO',
                'SAN VICENTE TANCUAYALAB',
                'SANTA CATARINA',
                'SANTA MARÍA DEL RÍO',
                'SOLEDAD DE GRACIANO SÁNCHEZ',
                'TAMASOPO',
                'TAMAZUNCHALE',
                'TAMPACÁN',
                'TAMPAMOLÓN CORONA',
                'TAMUÍN',
                'TANLAJÁS',
                'TANQUIÁN DE ESCOBEDO',
                'TIERRA NUEVA',
                'VANEGAS',
                'VENADO',
                'VILLA DE ARRIAGA',
                'VILLA DE GUADALUPE',
                'VILLA DE LA PAZ',
                'VILLA DE RAMOS',
                'VILLA DE REYES',
                'VILLA HIDALGO',
                'VILLA JUÁREZ',
                'XILITLA',
                'ZARAGOZA',
            ],
            28 => [
                'ABASOLO',
                'ALDAMA',
                'ALTAMIRA',
                'ANTIGUO MORELOS',
                'BURGOS',
                'BUSTAMANTE',
                'CAMARGO',
                'CASAS',
                'CIUDAD MADERO',
                'CRUILLAS',
                'EL MANTE',
                'GÓMEZ FARÍAS',
                'GONZÁLEZ',
                'GÜÉMEZ',
                'GUERRERO',
                'GUSTAVO DÍAZ ORDAZ',
                'HIDALGO',
                'JAUMAVE',
                'JIMÉNEZ',
                'LLERA',
                'MAINERO',
                'MATAMOROS',
                'MÉNDEZ',
                'MIER',
                'MIGUEL ALEMÁN',
                'MIQUIHUANA',
                'NUEVO LAREDO',
                'NUEVO MORELOS',
                'OCAMPO',
                'PADILLA',
                'PALMILLAS',
                'REYNOSA',
                'RÍO BRAVO',
                'SAN CARLOS',
                'SAN FERNANDO',
                'SAN NICOLÁS',
                'SOTO LA MARINA',
                'TAMPICO',
                'TULA',
                'VALLE HERMOSO',
                'VICTORIA',
                'VILLAGRÁN',
                'XICOTÉNCATL',
            ],
            6 => [
                'ARMERÍA',
                'COLIMA',
                'COMALA',
                'COQUIMATLÁN',
                'CUAUHTÉMOC',
                'IXTLAHUACÁN',
                'MANZANILLO',
                'MINATITLÁN',
                'TECOMÁN',
                'VILLA DE ÁLVAREZ'
            ],
            14 => [
                'ACATIC',
                'ACATLÁN DE JUÁREZ',
                'AHUALULCO DE MERCADO',
                'AMACUECA',
                'AMATITÁN',
                'AMECA',
                'ARANDAS',
                'ATEMAJAC DE BRIZUELA',
                'ATENGO',
                'ATENGUILLO',
                'ATOTONILCO EL ALTO',
                'ATOYAC',
                'AUTLÁN DE NAVARRO',
                'AYOTLÁN',
                'AYUTLA',
                'BOLAÑOS',
                'CABO CORRIENTES',
                'CASIMIRO CASTILLO',
                'CAÑADAS DE OBREGÓN',
                'CHAPALA',
                'CHIMALTITÁN',
                'CHIQUILISTLÁN',
                'CIHUATLÁN',
                'COCULA',
                'COLOTLÁN',
                'CONCEPCIÓN DE BUENOS AIRES',
                'CUAUTITLÁN DE GARCÍA BARRAGÁN',
                'CUAUTLA',
                'CUQUÍO',
                'DEGOLLADO',
                'EJUTLA',
                'EL ARENAL',
                'EL GRULLO',
                'EL LIMÓN',
                'EL SALTO',
                'ENCARNACIÓN DE DÍAZ',
                'ETZATLÁN',
                'GÓMEZ FARÍAS',
                'GUACHINANGO',
                'GUADALAJARA',
                'HOSTOTIPAQUILLO',
                'HUEJÚCAR',
                'HUEJUQUILLA EL ALTO',
                'IXTLAHUACÁN DE LOS MEMBRILLOS',
                'IXTLAHUACÁN DEL RÍO',
                'JALOSTOTITLÁN',
                'JAMAY',
                'JESÚS MARÍA',
                'JILOTLÁN DE LOS DOLORES',
                'JOCOTEPEC',
                'JUANACATLÁN',
                'JUCHITLÁN',
                'LA BARCA',
                'LA HUERTA',
                'LA MANZANILLA DE LA PAZ',
                'LAGOS DE MORENO',
                'MAGDALENA',
                'MASCOTA',
                'MAZAMITLA',
                'MEXTICACÁN',
                'MEZQUITIC',
                'MIXTLÁN',
                'OCOTLÁN',
                'OJUELOS DE JALISCO',
                'PIHUAMO',
                'PONCITLÁN',
                'PUERTO VALLARTA',
                'QUITUPAN',
                'SAN CRISTÓBAL DE LA BARRANCA',
                'SAN DIEGO DE ALEJANDRÍA',
                'SAN GABRIEL',
                'SAN IGNACIO CERRO GORDO',
                'SAN JUAN DE LOS LAGOS',
                'SAN JULIÁN',
                'SAN MARCOS',
                'SAN MARTÍN DE BOLAÑOS',
                'SAN MARTÍN HIDALGO',
                'SAN MIGUEL EL ALTO',
                'SAN PEDRO TLAQUEPAQUE',
                'SAN SEBASTIÁN DEL OESTE',
                'SANTA MARÍA DE LOS ÁNGELES',
                'SAYULA',
                'TALPA DE ALLENDE',
                'TAMAZULA DE GORDIANO',
                'TAPALPA',
                'TECALITLÁN',
                'TECHALUTA DE MONTENEGRO',
                'TECOLOTLÁN',
                'TENAMAXTLÁN',
                'TEOCALTICHE',
                'TEOCUITATLÁN DE CORONA',
                'TEPATITLÁN DE MORELOS',
                'TEQUILA',
                'TEUCHITLÁN',
                'TIZAPÁN EL ALTO',
                'TLAJOMULCO DE ZÚÑIGA',
                'TLAQUEPAQUE',
                'TOLIMÁN',
                'TOMATLÁN',
                'TONALÁ',
                'TONAYA',
                'TONILA',
                'TOTATICHE',
                'TOTOTLÁN',
                'TUXCACUESCO',
                'TUXCUECA',
                'TUXPAN',
                'UNIÓN DE SAN ANTONIO',
                'UNIÓN DE TULA',
                'VALLE DE GUADALUPE',
                'VALLE DE JUÁREZ',
                'VILLA CORONA',
                'VILLA GUERRERO',
                'VILLA HIDALGO',
                'VILLA PURIFICACIÓN',
                'YAHUALICA DE GONZÁLEZ GALLO',
                'ZACOALCO DE TORRES',
                'ZAPOPAN',
                'ZAPOTILTIC',
                'ZAPOTITLÁN DE VADILLO',
                'ZAPOTLÁN DEL REY',
                'ZAPOTLÁN EL GRANDE',
                'ZAPOTLANEO',
                'ZOAPILTEPEC',
            ],
            1 => [
                'AGUASCALIENTES',
                'ASIENTOS',
                'CALVILLO',
                'COSÍO',
                'JESÚS MARÍA',
                'PABELLÓN DE ARTEAGA',
                'RINCÓN DE ROMOS',
                'SAN JOSÉ DE GRACIA',
                'TEPEZALÁ',
                'EL LLANO',
                'SAN FRANCISCO DE LOS ROMO',
            ],
            18 => [
                'ACAPONETA',
                'AHUACATLÁN',
                'AMATLÁN DE CAÑAS',
                'COMPOSTELA',
                'HUAJICORI',
                'IXTLÁN DEL RÍO',
                'JALA',
                'LA YESCA',
                'ROSAMORADA',
                'RUÍZ',
                'SAN BLAS',
                'SAN PEDRO LAGUNILLAS',
                'SANTA MARÍA DEL ORO',
                'SANTIAGO IXCUINTLA',
                'TECUALA',
                'TEPIC',
                'TUXPAN',
                'DEL NAYAR',
                'BAHÍA DE BANDERAS',
                'VILLA HIDALGO'
            ],
            32 => [
                'APOZOL',
                'APULCO',
                'ATOLINGA',
                'BENITO JUÁREZ',
                'CALERA',
                'CAÑITAS DE FELIPE PESCADOR',
                'CHALCHIHUITES',
                'CONCEPCIÓN DEL ORO',
                'CUAUHTÉMOC',
                'EL PLATEADO DE JOAQUÍN AMARO',
                'EL SALVADOR',
                'FRESNILLO',
                'GENARO CODINA',
                'GENERAL ENRIQUE ESTRADA',
                'GENERAL FRANCISCO R. MURGUÍA',
                'GENERAL PANFILO NATERA',
                'GUADALUPE',
                'HUANUSCO',
                'JALPA',
                'JEREZ',
                'JIMÉNEZ DEL TEUL',
                'JUAN ALDAMA',
                'JUCHIPILA',
                'LORETO',
                'LUIS MOYA',
                'MAZAPIL',
                'MELCHOR OCAMPO',
                'MEZQUITAL DEL ORO',
                'MIGUEL AUZA',
                'MOMAX',
                'MONTE ESCOBEDO',
                'MORELOS',
                'MOYAHUA DE ESTRADA',
                'NOCHISTLÁN DE MEJÍA',
                'NORIA DE ÁNGELES',
                'OJOCALIENTE',
                'PÁNUCO',
                'PINOSUELOS',
                'RÍO GRANDE',
                'SAIN ALTO',
                'SANTA MARÍA DE LA PAZ',
                'SOMBRERETE',
                'SUSTICACÁN',
                'TABASCO',
                'TEPECHITLÁN',
                'TEPETONGO',
                'TEUL DE GONZÁLEZ ORTEGA',
                'TLALTENANGO DE SÁNCHEZ ROMÁN',
                'TRANCOSO',
                'TRINIDAD GARCÍA DE LA CADENA',
                'VALPARAÍSO',
                'VETAGRANDE',
                'VILLA DE COS',
                'VILLA GARCÍA',
                'VILLA GONZÁLEZ ORTEGA',
                'VILLA HIDALGO',
                'VILLANUEVA',
                'ZACATECAS',
            ],
            19 => [
                'ABASOLO',
                'AGUALEGUAS',
                'ALLENDE',
                'ANÁHUAC',
                'APODACA',
                'ARAMBERRI',
                'BUSTAMANTE',
                'CADEREYTA JIMÉNEZ',
                'CERRALVO',
                'CHINA',
                'CIÉNEGA DE FLORES',
                'DOCTOR ARROYO',
                'DOCTOR COSS',
                'DOCTOR GONZÁLEZ',
                'EL CARMEN',
                'GALEANA',
                'GARCÍA',
                'GENERAL BRAVO',
                'GENERAL ESCOBEDO',
                'GENERAL TERÁN',
                'GENERAL TREVIÑO',
                'GENERAL ZARAGOZA',
                'GENERAL ZUAZUA',
                'GUADALUPE',
                'HIDALGO',
                'HIGUERAS',
                'HUALAHUISES',
                'ITURBIDE',
                'JUÁREZ',
                'LAMPAZOS DE NARANJO',
                'LINARES',
                'LOS ALDAMAS',
                'LOS HERRERAS',
                'LOS RAMONES',
                'MARÍN',
                'MELCHOR OCAMPO',
                'MIER Y NORIEGA',
                'MINA',
                'MONTEMORELOS',
                'MONTERREY',
                'PARÁS',
                'PESQUERÍA',
                'RAYONES',
                'SABINAS HIDALGO',
                'SALINAS VICTORIA',
                'SAN NICOLÁS DE LOS GARZA',
                'SAN PEDRO GARZA GARCÍA',
                'SANTA CATARINA',
                'SANTIAGO',
                'VALLE HERMOSO',
                'VILLALDAMA',
            ],
            10 => [
                'CANATLÁN',
                'CANELAS',
                'CONETO DE COMONFORT',
                'CUENCAMÉ',
                'DURANGO',
                'EL ORO',
                'GENERAL SIMÓN BOLÍVAR',
                'GÓMEZ PALACIO',
                'GUADALUPE VICTORIA',
                'GUANACEVÍ',
                'HIDALGO',
                'INDÉ',
                'LERDO',
                'MAPIMÍ',
                'MEZQUITAL',
                'NAZAS',
                'NOMBRE DE DIOS',
                'OCAMPO',
                'OTÁEZ',
                'PÁNUCO DE CORONADO',
                'PEÑÓN BLANCO',
                'POANAS',
                'PUEBLO NUEVO',
                'RODEO',
                'SAN BERNARDO',
                'SAN DIMAS',
                'SAN JUAN DE GUADALUPE',
                'SAN JUAN DEL RÍO',
                'SAN LUIS DEL CORDERO',
                'SAN PEDRO DEL GALLO',
                'SANTIAGO PAPASQUIARO',
                'SÚCHIL',
                'TAMAZULA',
                'TEPEHUANES',
                'TLAHUALILO',
                'TOPIA',
                'VICENTE GUERRERO',
                'NUEVO IDEAL'
            ],
            8 => [
                'AHUMADA',
                'ALDAMA',
                'ALLENDE',
                'AQUILES SERDÁN',
                'ASCENSIÓN',
                'BACHÍNIVA',
                'BALLEZA',
                'BATOPILAS DE MANUEL GÓMEZ MORÍN',
                'BOCOYNA',
                'BUENAVENTURA',
                'CAMARGO',
                'CARICHÍ',
                'CASAS GRANDES',
                'CORONADO',
                'COYAME DEL SOTOL',
                'CUAUHTÉMOC',
                'CUSIHUIRIACHI',
                'CHIHUAHUA',
                'CHÍNIPAS',
                'DELICIAS',
                'DR. BELISARIO DOMÍNGUEZ',
                'EL TULE',
                'GALEANA',
                'GÓMEZ FARÍAS',
                'GRAN MORELOS',
                'GUACHOCHI',
                'GUADALUPE',
                'GUADALUPE Y CALVO',
                'GUAZAPARES',
                'GUERRERO',
                'HIDALGO DEL PARRAL',
                'HUEJOTITÁN',
                'IGNACIO ZARAGOZA',
                'JANOS',
                'JIMÉNEZ',
                'JUÁREZ',
                'JULIMES',
                'LA CRUZ',
                'LOPEZ',
                'MADERA',
                'MAGUARICHI',
                'MANUEL BENAVIDES',
                'MATACHÍ',
                'MATAMOROS',
                'MEOQUI',
                'MORELOS',
                'MORIS',
                'NAMIQUIPA',
                'NONOAVA',
                'NUEVO CASAS GRANDES',
                'OCAMPO',
                'OJINAGA',
                'PRAXEDIS G. GUERRERO',
                'RIVA PALACIO',
                'ROSARIO',
                'SAN FRANCISCO DE BORJA',
                'SAN FRANCISCO DE CONCHOS',
                'SAN FRANCISCO DEL ORO',
                'SANTA BÁRBARA',
                'SATEVÓ',
                'SAUCILLO',
                'TEMÓSACHI',
                'URIQUE',
                'URUACHI',
                'VALLE DE ZARAGOZA'
            ],
            25 => [
                'AHOME',
                'ANGOSTURA',
                'BADIRAGUATO',
                'CONCORDIA',
                'COSALÁ',
                'CULIACÁN',
                'CHOIX',
                'EL FUERTE',
                'ELOTA',
                'ESCUINAPA',
                'GUASAVE',
                'MAZATLÁN',
                'MOCORITO',
                'NAVOLATO',
                'ROSARIO',
                'SALVADOR ALVARADO',
                'SAN IGNACIO',
                'SINALOA',
            ],
            26 => [
                'ACONCHI',
                'AGUAPRIETA',
                'ÁLAMOS',
                'ALTAR',
                'ARIVECHI',
                'ARIZPE',
                'ÁTIL',
                'BACADÉHUACHI',
                'BACANORA',
                'BÁCERAC',
                'BACOACHI',
                'BÁCUM',
                'BANÁMICHI',
                'BAVIACORA',
                'BAVISPE',
                'BENITO JUÁREZ',
                'BENJAMÍN HILL',
                'CABORCA',
                'CAJEME',
                'CANANEA',
                'CARBÓ',
                'CUCURPE',
                'CUMPAS',
                'DIVISADEROS',
                'EMPALME',
                'ETCHOJOA',
                'FRONTERAS',
                'GENERAL PLUTARCO ELÍAS CALLES',
                'GRANADOS',
                'GUAYMAS',
                'HERMOSILLO',
                'HUACHINERA',
                'HUÁSABAS',
                'HUATABAMPO',
                'HUÉPAC',
                'IMURIS',
                'LA COLORADA',
                'MAGDALENA',
                'MAZATÁN',
                'MOCTEZUMA',
                'NACO',
                'NÁCORI CHICO',
                'NACOZARI DE GARCÍA',
                'NAVOJOA',
                'NOGALES',
                'ÓNAVAS',
                'OPODEPE',
                'OQUITOA',
                'PITIQUITO',
                'PUERTO PEÑASCO',
                'QUIRIEGO',
                'RAYÓN',
                'ROSARIO',
                'SAHUARIPA',
                'SAN FELIPE DE JESÚS',
                'SAN IGNACIO RÍO MUERTO',
                'SAN JAVIER',
                'SAN LUIS RÍO COLORADO',
                'SAN MIGUEL DE HORCASITAS',
                'SAN PEDRO DE LA CUEVA',
                'SANTA ANA',
                'SANTA CRUZ',
                'SÁRIC',
                'SOYOPA',
                'SUAQUI GRANDE',
                'TEPACHE',
                'TRINCHERAS',
                'TUBUTAMA',
                'URES',
                'VILLA HIDALGO',
                'VILLA PESQUEIRA',
                'YÉCORA',
            ],
            2 => [
                'ENSENADA',
                'MEXICALI',
                'TECATE',
                'TIJUANA',
                'PLAYAS DE ROSARITO',
                'SAN QUINTÍN',
                'SAN FELIPE',
            ],
            3 => [
                'COMONDÚ',
                'MULEGÉ',
                'LA PAZ',
                'LOS CABOS',
                'LORETO',
            ],
        ];

        foreach ($municipiosPorEstado as $stateId => $municipios) {
            foreach ($municipios as $nombre) {
                // Asegura mayúsculas (con acentos ya incluidos)
                $nombre = mb_strtoupper($nombre, 'UTF-8');

                // Verifica si ya existe el municipio con ese state_id
                $existe = DB::table('counties')
                    ->where('name', $nombre)
                    ->where('state_id', $stateId)
                    ->exists();

                if (!$existe) {
                    DB::table('counties')->insert([
                        'name' => $nombre,
                        'state_id' => $stateId,
                        'status' => 'active',
                        'modified_by' => null,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);
                }
            }
        }
    }
}
